/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.diseño;

import com.conexion.Connections;
import com.create_txt.CreateFile;
import com.model.*;
import java.sql.*;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Runaw
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btlogin = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        contraseñaLogin = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        userLogin = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setMaximumSize(new java.awt.Dimension(243, 462));
        jPanel2.setMinimumSize(new java.awt.Dimension(243, 462));
        jPanel2.setPreferredSize(new java.awt.Dimension(243, 462));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btlogin.setBackground(new java.awt.Color(191, 13, 13));
        btlogin.setFont(new java.awt.Font("Poppins", 1, 11)); // NOI18N
        btlogin.setForeground(new java.awt.Color(255, 255, 255));
        btlogin.setText("Ingresar");
        btlogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btloginMouseClicked(evt);
            }
        });
        btlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btloginActionPerformed(evt);
            }
        });
        jPanel2.add(btlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 140, 40));

        jLabel4.setFont(new java.awt.Font("Poppins SemiBold", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Contraseña");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        contraseñaLogin.setFont(new java.awt.Font("Poppins", 1, 11)); // NOI18N
        contraseñaLogin.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        contraseñaLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        contraseñaLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contraseñaLoginActionPerformed(evt);
            }
        });
        jPanel2.add(contraseñaLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 140, -1));

        jLabel2.setFont(new java.awt.Font("Poppins SemiBold", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Usuario");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));

        userLogin.setFont(new java.awt.Font("Poppins", 1, 11)); // NOI18N
        userLogin.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        userLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        userLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userLoginActionPerformed(evt);
            }
        });
        jPanel2.add(userLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 140, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/identidad-login.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 330, 400));

        background.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 324, 346));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/imagen-fondo.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        background.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void contraseñaLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contraseñaLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contraseñaLoginActionPerformed

    private void btloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btloginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btloginActionPerformed

    private void btloginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btloginMouseClicked
        try {
            //Parameters
            long id = -1;
            String identificacion = null;
            String nombre = null;
            String apellido = null;
            String correo = null;
            int semestre = 0;
            String facultad = null;
            String programa = null;
            int rol_id = 0;

            //other parameters
            com.login.Login log = new com.login.Login();

            com.diseño.MenuAdmin menuAdmin = new com.diseño.MenuAdmin();
            com.diseño.MenuAsistente menuAsistente = new com.diseño.MenuAsistente();
            com.diseño.MenuDirector menuDirector = new com.diseño.MenuDirector();
            com.diseño.MenuEstudiante menuEstudiante = new com.diseño.MenuEstudiante();

            Connections con = new com.conexion.Connections();

            Statement instruccion = con.conexion();

            String user = userLogin.getText();
            String contra = contraseñaLogin.getText();
            String resultado_l = log.login(user, contra);

            if (user.equals("admin") && contra.equals("admin")) {
                menuAdmin.setVisible(true);
            } else if (resultado_l.equals("usuario no encontrado")){
                JOptionPane.showMessageDialog(null, "Usuario no encontrado");
            } else if(resultado_l.equals("las credenciales no coinciden")){
                JOptionPane.showMessageDialog(null, "Las credenciales no coinciden");
            } else {
                  
                System.out.println(resultado_l);

                //queries
                String query = "SELECT * FROM %s WHERE correo_institucional = \"%s\";".formatted(resultado_l.split(" ")[2], user);

                ResultSet result = instruccion.executeQuery(query);

                if (resultado_l.split(" ")[2].equals("estudiante")) {
                    while (result.next()) {
                        id = result.getLong("id_estudiante");
                        identificacion = result.getString("identificacion");
                        nombre = result.getString("nombre");
                        apellido = result.getString("apellido");
                        correo = result.getString("correo_institucional");
                        semestre = result.getInt("semestre");
                        facultad = result.getString("nombre_facultad");
                        programa = result.getString("nombre_programa");

                    }

                    Estudiante estudiante = new Estudiante(id, identificacion, nombre, apellido, correo, semestre, facultad, programa);
                    
                    givePersona(estudiante);
                    menuEstudiante.setVisible(true);

                } else if (resultado_l.split(" ")[2].equals("personal")) {
                    while (result.next()) {
                        id = result.getLong("id_personal");
                        identificacion = result.getString("identificacion");
                        nombre = result.getString("nombre");
                        apellido = result.getString("apellido");
                        correo = result.getString("correo_institucional");
                        facultad = result.getString("nombre_facultad");
                        programa = result.getString("nombre_programa");
                        rol_id = result.getInt("rol_id");

                    }
                    if (rol_id == 2) {
                        Director director = new Director(id, rol_id, identificacion, nombre, apellido, correo, facultad, programa);
                        givePersona(director);

                        menuDirector.setVisible(true);

                    } else {
                        Asistente asistente = new Asistente(id, rol_id, identificacion, nombre, apellido, correo, facultad, programa);
                        givePersona(asistente);
                        menuAsistente.setVisible(true);
                        

                    }

                } 
            }
            this.dispose();
// TODO add your handling code here:
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        CreateFile file = new CreateFile();
        
        file.createTxt(userLogin.getText(), contraseñaLogin.getText());
        
    }//GEN-LAST:event_btloginMouseClicked

    
    private void userLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userLoginActionPerformed

    public Persona givePersona(Persona persona){
        return persona;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JButton btlogin;
    private javax.swing.JTextField contraseñaLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField userLogin;
    // End of variables declaration//GEN-END:variables
}
