call sistematickets.insertPrograma("tecnologia en gestion de marketing", "ciencias economicas, administrativas y contables");
call sistematickets.insertPrograma("administracion en seguridad y salud en el trabajo", "ciencias economicas, administrativas y contables");
call sistematickets.insertPrograma("ingenieria civil", 'ingenieria');
call sistematickets.insertPrograma("tecnologia en produccion industrial", 'ingenieria');
call sistematickets.insertPrograma("tecnologia en seguridad e higiene ocupacional", 'ingenieria');
call sistematickets.insertPrograma("tecnologia en control de calidad", 'ingenieria');
call sistematickets.insertPrograma("tecnologia en gestion ambiental industrial", 'ingenieria');
call sistematickets.insertPrograma("tecnologia en operacion de plantas y procesos industriales", 'ingenieria');
call sistematickets.insertPrograma("tecnologia en instrumentacion industrial", 'ingenieria');
call sistematickets.insertPrograma("tecnologia en control electronico de procesos", 'ingenieria');
call sistematickets.insertPrograma("tecnologia en desarrollo de software", 'ingenieria');
call sistematickets.insertPrograma("tecnologia en redes de comunicaciones y servicios convergentes", 'ingenieria');
call sistematickets.insertPrograma("ingenieria industrial", 'ingenieria');
call sistematickets.insertPrograma("derecho", 'ciencias sociales y humanas');
call sistematickets.insertPrograma("psicologia", 'ciencias sociales y humanas');
call sistematickets.insertPrograma("trabajo social", 'ciencias sociales y humanas');
call sistematickets.insertPrograma("tecnologia en gestion turistica y hotelera", 'ciencias economicas, administrativas y contables');
call sistematickets.insertPrograma("tecnologia en gestion logistica y portuaria", 'ciencias economicas, administrativas y contables');
call sistematickets.insertPrograma("tecnologia en gestion de negocios internacionales", 'ciencias economicas, administrativas y contables');
call sistematickets.insertPrograma("tecnologia en gestion financiera", 'ciencias economicas, administrativas y contables');
call sistematickets.insertPrograma("tecnologia en contabilidad sistematizada", 'ciencias economicas, administrativas y contables');
call sistematickets.insertPrograma("contaduria publica", 'ciencias economicas, administrativas y contables');
call sistematickets.insertPrograma("ingenieria de procesos", 'ingenieria');
call sistematickets.insertPrograma("ingenieria de sistemas", 'ingenieria');
call sistematickets.insertPrograma("administracion de empresas", 'ciencias economicas, administrativas y contables');
call sistematickets.insertPrograma("ingenieria electronica", 'ingenieria');
call sistematickets.insertPrograma("ingenieria ambiental", 'ingenieria');
call sistematickets.insertPrograma("especializacion en finanzas", 'ciencias economicas, administrativas y contables');
call sistematickets.insertPrograma("especializacion en gestion tributaria", 'ciencias economicas, administrativas y contables');
call sistematickets.insertPrograma("especializacion en gerencia de proyectos", 'ciencias economicas, administrativas y contables');
call sistematickets.insertPrograma("especializacion en gerencia estrategica de marketing", 'ciencias economicas, administrativas y contables');
call sistematickets.insertPrograma("especializacion en gestion estrategica del talento humano", 'ciencias economicas, administrativas y contables');
call sistematickets.insertPrograma("especializacion en logistica y distribucion fisica internacional", 'ciencias economicas, administrativas y contables');
call sistematickets.insertPrograma("especializacion psicologia social aplicada", 'ciencias sociales y humanas');
call sistematickets.insertPrograma("especializacion en gestion integral en hseq", 'ingenieria');
call sistematickets.insertPrograma("maestria en sistemas de gestion", 'ingenieria');
call sistematickets.insertPrograma("maestria en tecnologias de la informacion y la comunicacion", 'ingenieria');

select * from programa;